### ISSUE TITLE
t/20_unknown.t fails with Perl 5.35.10 + JSON::PP 4.08

### ISSUE THREAD

**Issue by plicease** [rurban/Cpanel-JSON-XS#194]
https://gist.github.com/plicease/249034d9dc0e35ba759d1cd74f6c8fd8

I was not able to reproduce this with Perl 5.35.9 or JSON::PP 4.07.

This may be related:
https://metacpan.org/release/ISHIGAKI/JSON-PP-4.08/source/Changes#L5

**Comment by DrHyde** [comment]
This seems to still be broken in latest blead:

```
Running make test for RURBAN/Cpanel-JSON-XS-4.28.tar.gz
"/Users/cpantesting/cpantesting/perl-blead/bin/perl5.35.12" -MExtUtils::Command::MM -e 'cp_nonempty' -- XS.bs blib/arch/auto/Cpanel/JSON/XS/XS.bs 644
PERL_DL_NONLAZY=1 "/Users/cpantesting/cpantesting/perl-blead/bin/perl5.35.12" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00_load.t ................ ok
t/01_utf8.t ................ ok
t/02_error.t ............... ok
...
t/20_faihu.t ............... ok
Subroutine JSON::PP::Boolean::(0+ redefined at /Users/cpantesting/cpantesting/perl-blead/lib/5.35.12/overload.pm line 52.
Subroutine JSON::PP::Boolean::(-- redefined at /Users/cpantesting/cpantesting/perl-blead/lib/5.35.12/overload.pm line 52.
Subroutine JSON::PP::Boolean::(++ redefined at /Users/cpantesting/cpantesting/perl-blead/lib/5.35.12/overload.pm line 52.

#   Failed test 'pp sv_yes'
#   at t/20_unknown.t line 57.
#          got: '{"true":1}'
#     expected: '{"true":true}'

#   Failed test 'pp sv_no'
#   at t/20_unknown.t line 58.
#          got: '{"false":""}'
#     expected: '{"false":false}'

#   Failed test 'pp sv_no'
#   at t/20_unknown.t line 59.
#          got: '{"false":""}'
#     expected: '{"false":false}'
# Looks like you failed 3 tests of 32.
t/20_unknown.t .............
Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/32 subtests
```

**Comment by rurban** [comment]
Yes, saw the reports. couldn't repro it locally so far.

**Comment by DrHyde** [comment]
On this machine (Intel Mac, OSX 11.6.5) it's reproducible on perl commit 824d526 (I don't think there's nothing special about this commit, it's just where the head of the blead branch was when I built it this weekend) thus:

```
$ sh Configure -de -Dprefix=$HOME/perl-blead -Dusedevel
$ make
$ make test
$ make install
$ $HOME/perl-blead/bin/cpan5.35.12 -t Cpanel::JSON::XS
```

**Comment by plicease** [comment]
I saw this failure with the current version on 5.35.11 or .12 (can't remember which), but upgrading `JSON::PP` seemed to fix it.  Sorry I don't have the relevant versions available.

**Comment by DrHyde** [comment]
Ah, looks like blead just needs to be updated to have the new JSON::PP, which is distributed with perl but maintained on CPAN

**Comment by rurban** [comment]
So the test is wrong. It needs to check JSON::PP::VERSION 
Thanks

**Comment by rjbs** [comment]
@rurban I think there's some contention over the change in JSON::PP here, and you probably shouldn't make a new release until it's settled.  I'll let you know ASAP, because this is a problem for the release of v5.36.0.  I don't want you to waste your time now when I'm going to ask you to hurry later. :)

**Comment by rjbs** [comment]
@rurban Okay, here's the summary we went to p5p: http://nntp.perl.org/group/perl.perl5.porters/263731

Basically:  We (PSC) think the change in JSON::PP is a bit of a time bomb at this point.  Your test for perl version instead of JSON::PP was a bug, but it was a bug that helped alert us to this.  Thanks! 🤪

charsbar is going to make a new JSON::PP that does not rely on is_bool, for now.  It may be reintroduced at some future time, with a longer break-in period.  When that is released (some time this weekend, I expect), I think the correct next step is for you to release a Cpanel::JSON::XS that goes back to its previous behavior, ignoring perl version and JSON::PP version, and treats the behavior of JSON::PP v4.08 as a fluke.

Sound good?

**Comment by rurban** [comment]
Thanks for doing this, sounds good.

But sooner or later somebody else will start to use the new shiny tools...

**Comment by rjbs** [comment]
@rurban A new JSON::PP, v4.09, has been released.  Could you make a new Cpanel::JSON::XS release (soon! 🙂) that gets rid of the core-bools-if-v5.35+ check?

(I expect someone will want to bring it back in the future, but doing it right as we release v5.36 feels like it'll be a bad surprise for too many people.)

**Comment by rurban** [comment]
pushed as relprep

**Comment by rjbs** [comment]
@rurban It would be great if you could make this release soon.  I think v5.36 is ready to go, but I'd rather not people hit this snag immediately after install!  Thanks.

**Comment by rjbs** [comment]
I saw this happened.  Thanks!
